/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/button/index.vue')['default']
    ButtonIcon: typeof import('./components/button/icon.vue')['default']
    ButtonToggleTheme: typeof import('./components/button/toggle-theme.vue')['default']
    Card: typeof import('./components/card.vue')['default']
    LayoutAppBar: typeof import('./components/layout/app-bar.vue')['default']
    LayoutFooter: typeof import('./components/layout/footer.vue')['default']
    LayoutHeader: typeof import('./components/layout/header.vue')['default']
    LayoutNav: typeof import('./components/layout/nav.vue')['default']
    NavLink: typeof import('./components/nav/link.vue')['default']
    Pager: typeof import('./components/pager.vue')['default']
    PuzzleGame: typeof import('./components/PuzzleGame.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./components/spacer.vue')['default']
    Square: typeof import('./components/Square.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TitleH2: typeof import('./components/title/h2.vue')['default']
    TitleH3: typeof import('./components/title/h3.vue')['default']
    TitleMain: typeof import('./components/title/main.vue')['default']
  }
}
