/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/button/index.vue')['default']
    ButtonIcon: typeof import('./components/button/icon.vue')['default']
    ButtonToggleTheme: typeof import('./components/button/toggle-theme.vue')['default']
    Card: typeof import('./components/card.vue')['default']
    CardCompany: typeof import('./components/card/company.vue')['default']
    CardStudy: typeof import('./components/card/study.vue')['default']
    LayoutAppBar: typeof import('./components/layout/app-bar.vue')['default']
    LayoutFooter: typeof import('./components/layout/footer.vue')['default']
    LayoutHeader: typeof import('./components/layout/header.vue')['default']
    LayoutNav: typeof import('./components/layout/nav.vue')['default']
    Link: typeof import('./components/Link.vue')['default']
    LinkMini: typeof import('./components/link/mini.vue')['default']
    NavLink: typeof import('./components/nav/link.vue')['default']
    Pager: typeof import('./components/pager.vue')['default']
    Project: typeof import('./components/project.vue')['default']
    ProjectDetails: typeof import('./components/ProjectDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./components/spacer.vue')['default']
    TitleH2: typeof import('./components/title/h2.vue')['default']
    TitleH3: typeof import('./components/title/h3.vue')['default']
    TitleMain: typeof import('./components/title/main.vue')['default']
    VisualInfoGold: typeof import('./components/visual/info-gold.vue')['default']
  }
}
