/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/companies': RouteRecordInfo<
      '/companies',
      '/companies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/curriculum-vitae': RouteRecordInfo<
      '/curriculum-vitae',
      '/curriculum-vitae',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/legal': RouteRecordInfo<
      '/legal',
      '/legal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/privacy-policy': RouteRecordInfo<
      '/privacy-policy',
      '/privacy-policy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/[id]': RouteRecordInfo<
      '/projects/[id]',
      '/projects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/studies': RouteRecordInfo<
      '/studies',
      '/studies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/technologies': RouteRecordInfo<
      '/technologies',
      '/technologies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/companies.vue': {
      routes:
        | '/companies'
      views:
        | never
    }
    'src/pages/curriculum-vitae.vue': {
      routes:
        | '/curriculum-vitae'
      views:
        | never
    }
    'src/pages/legal.md': {
      routes:
        | '/legal'
      views:
        | never
    }
    'src/pages/privacy-policy.md': {
      routes:
        | '/privacy-policy'
      views:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
      views:
        | never
    }
    'src/pages/projects/index.vue': {
      routes:
        | '/projects/'
      views:
        | never
    }
    'src/pages/projects/[id].vue': {
      routes:
        | '/projects/[id]'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/studies.vue': {
      routes:
        | '/studies'
      views:
        | never
    }
    'src/pages/technologies.vue': {
      routes:
        | '/technologies'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
